Naming/MethodParameterName:
  AllowedNames:
    - k
    - h
    - n
    - x
    - y
    - z
    - t
    - q
    - a
    - b
    - m
    - r
    - p
  Enabled: true

Layout/LineLength:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
